import { Inter } from 'next/font/google';

import './globals.css'
import { HeaderStickyProvider } from '@/contexts/HeaderStickyContext';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',

});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={'dark ' + inter.className}>
      <body className='dark:bg-stone-800'>
        <HeaderStickyProvider>
          {children}
        </HeaderStickyProvider>
      </body>
    </html>
  )
}
